package com.ccoa.planeacionestrategica.infraestructura.adaptador.entidad.rubro.enums;

public enum ERubroIngresos {

    MERCANTIL,PROPONENTES,ESAL, E_E_S,RUNEOL,CONCILIACION_Y_ARBITRAJE, PUBLICIDAD,ARRENDAMIENTOS, RENDIMIENTOS_FINANCIEROS,
    COMISIONES, RECUPERACIONES, AFILIACIONES,CAPACITACIONES,FERIAS,DEPOSITO_DE_ESTADOS_FINANCIEROS, VENTA_DE_INFORMACION_COMERCIAL,
    HOJAS_FOLIADAS, COPIAS, DIVIDENDOS
}
