package com.ccoa.planeacionestrategica.infraestructura.adaptador.entidad.rubro.enums;

public enum ERubroGastos {

    GASTOS_DE_PERSONAL,HONORARIOS,IMPUESTOS,ARRENDAMIENTOS,CONTRIBUCIONES_Y_AFILIACIONES,SEGUROS,
    SERVICIOS_ASEO_Y_VIGILANCIA,SERVICIOS_PUBLICOS,SERVICIOS_PROCESAMIENTO_DE_DATOS,SERVICIOS_PERSONAL_TEMPORAL,
    SERVICIOS_PORTES_TELEGRAMAS,SERVICIOS_FLETES_Y_TRANSPORTE,GASTOS_LEGALES, MANTENIMIENTO_Y_REPARACIONES,ADECUACIONES_E_INSTALACIONES,
    GASTOS_DE_VIAJE,LIBROS_SUSCRIPCIONES_PERIODICOS,ELEMENTOS_DE_ASEO_Y_CAFETERIA,PAPELERIA_E_INSUMOS_DE_OFICINA,
    TAXIS_Y_BUSES,CASINOS_Y_RESTAURANTES,PUBLICIDAD_Y_PROPAGANDA,COMISION
}
