package com.ccoa.planeacionestrategica.dominio.transversal.mensaje;

import lombok.experimental.UtilityClass;

@UtilityClass
public class Mensajes {
    public static final String NOMBRE_DE_LA_ACTIVIDAD_DE_LA_GESTION_DEL_AREA_NO_PUEDE_ESTAR_VACIA = "El nombre de la actividad de la gestión del area no puede estar vacía";
    public static final String NOMBRE_DEL_PROYECTO_NO_PUEDE_ESTAR_VACIA = "El nombre del proyecto no puede estar vacía";
    public static final String NOMBRE_DE_LA_ACTIVIDAD_ESTRATEGICA_NO_PUEDE_ESTAR_VACIA = "El nombre de la actividad estrategica no puede estar vacía";
    public static final String NOMBRE_DEL_AREA_NO_PUEDE_ESTAR_VACIO = "El nombre del area no puede estar vacío";
    public static final String NOMBRE_DEL_CARGO_NO_PUEDE_ESTAR_VACIO = "El nombre del cargo no puede estar vacío";
    public static final String NOMBRE_DEL_PAT_NO_PUEDE_ESTAR_VACIO = "El nombre del pat no puede estar vacío";
    public static final String NOMBRE_DE_LA_TAREA_NO_PUEDE_ESTAR_VACIO = "El nombre de la tarea no puede estar vacía";
    public static final String NOMBRE_DEL_USUARIO_NO_PUEDE_ESTAR_VACIO = "El nombre del usuario no puede estar vacío";
    public static final String LOS_APELLIDO_DEL_USUARIO_NO_PUEDE_ESTAR_VACIO = "Los apellidos del usuario no puede estar vacío";
    public static final String EL_PROCESO_NO_PUEDE_ESTAR_VACIO = "El proceso no puede estar vacía";
    public static final String EL_ESTADO_DE_LA_TAREA_NO_PUEDE_ESTAR_VACIO = "El estado de la tarea no puede estar vacía";
    public static final String EL_PRESUPUESTO_DEL_PROYECTO_NO_PUEDE_ESTAR_VACIO = "El presupuesto del proyecto no puede ser vacío";
    public static final String LA_MODALIDAD_DEL_PROYECTO_NO_PUEDE_ESTAR_VACIO = "La modalidad del proyecto no puede ser vacío";
    public static final String EL_VALOR_EJECUTADO_DEL_PROYECTO_NO_PUEDE_ESTAR_VACIO = "El valor ejecutado del proyecto no puede ser vacío";
    public static final String LA_PLANEACION_DEL_PROYECTO_NO_PUEDE_ESTAR_VACIO = "La planeacion del proyecto no puede ser vacío";
    public static final String EL_NUMERO_TOTAL_DE_SPRINT_DEL_PROYECTO_NO_PUEDE_ESTAR_VACIO = "El numero total de sprint del proyecto no puede ser vacío";
    public static final String LA_DESCRIPCION_NO_PUEDE_ESTAR_VACIA = "La descripcion no puede estar vacia";
    public static final String LA_FECHA_ANUAL_NO_PUEDE_ESTAR_VACIO = "El año no puede estar vacíao";
    public static final String LA_FECHA_INICIAL_NO_PUEDE_ESTAR_VACIA = "La fecha inicial no puede estar vacía";
    public static final String LA_FECHA_FINAL_NO_PUEDE_ESTAR_VACIA = "La fecha final no puede estar vacía";
    public static final String LAS_FECHAS_DEBEN_DE_COINCIDIR_CON_LOS_TIEMPOS_VALIDOS_DEL_SPRINT = "La fechas deben de coincidir con los tiempos validos de un sprint";
    public static final String LA_FECHA_FINAL_DEBE_SER_MAYOR_A_LA_FECHA_INICIAL = "La fecha final debe ser mayor a la fecha inicial";
    public static final String LA_FECHA_REGISTRO_DEBE_SER_LA_FECHA_ACTUAL = "La fecha de registro debe ser la fecha actual";
    public static final String LA_DURACION_NO_PUEDE_SER_NEGATIVA = "La duracion no puede ser negativa";
    public static final String LOS_DIAS_RESTANTES_NO_PUEDEN_SER_NULOS = "Los días restantes no pueden ser nulos";
    public static final String EL_PORCENTAJE_DE_AVANCE_NO_PUEDE_ESTAR_VACIO = "El porcentaje de avance no puede estar vacío";
    public static final String RUTA_ARCHIVO_DEL_DOCUMENTO_NO_PUEDE_ESTAR_VACIO = "La ruta del archivo del documento no puede estar vacio";
    public static final String LA_CONTRASENA_NO_CUENTA_CON_EL_PATRON_DE_SEGURIDAD_CORRRECTO = "La contraseña no cuenta con el patrón de seguridad correcto";
    public static final String EL_CORREO_NO_CUENTA_CON_EL_FORMATO_CORRRECTO = "El correo no cuenta con el formato correcto";
    public static final String EL_USUARIO_NO_PUEDE_EXISTIR_SIN_UN_ROL = "El usuario no puede existir sin un rol";
    public static final String NO_PUEDE_EXISTIR_SIN_USUARIO = "No puede existir sin usuario";
    public static final String NO_PUEDE_EXISTIR_SIN_AREA = "No puede existir sin area";
    public static final String NO_PUEDE_EXISTIR_SIN_CARGO = "No puede existir sin cargo";
    public static final String NO_PUEDE_EXISTIR_SIN_PAT = "No puede existir sin pat";
    public static final String NO_PUEDE_EXISTIR_SIN_PROYECTO = "No puede existir sin proyecto";
    public static final String NO_PUEDE_EXISTIR_SIN_ACTIVIDAD_ESTRATEGICA = "No puede existir sin actividad estrategica";
    public static final String NO_EXISTE_EL_SPRINT_CON_LOS_DATOS_INGRESADOS = "No existe el sprint con los datos ingresados";
    public static final String NO_EXISTE_LA_ACTIVIDAD_ESTRATEGICA_CON_LOS_DATOS_INGRESADOS = "No existe la Actividad estrategica con los datos ingresados";
    public static final String NO_EXISTE_LA_ACTIVIDAD_GESTION_DEL_AREA_CON_LOS_DATOS_INGRESADOS = "No existe la Actividad gestion del area con los datos ingresados";
    public static final String NO_EXISTE_LA_TAREA_CON_LOS_DATOS_INGRESADOS = "No existe la tarea con los datos ingresados";
    public static final String NO_EXISTE_EL_AREA_CON_LOS_DATOS_INGRESADOS = "No existe el area con los datos ingresados";
    public static final String NO_EXISTE_EL_CARGO_CON_LOS_DATOS_INGRESADOS = "No existe el cargo con los datos ingresados";
    public static final String NO_EXISTE_EL_PAT_CON_LOS_DATOS_INGRESADOS = "No existe el pat con los datos ingresados";
    public static final String NO_EXISTE_EL_PROYECTO_CON_LOS_DATOS_INGRESADOS = "No existe el proyecto con los datos ingresados";
    public static final String NO_EXISTE_EL_USUARIO_CON_LOS_DATOS_INGRESADOS = "No existe el usuario con los datos ingresados";
    public static final String NO_EXISTE_ACTIVIDAD_DE_GESTION_DE_LA_ACTIVIDAD_ESTRATEGICA_CON_LOS_DATOS_INGRESADOS = "No existe la actividad de gestion de la actividad estrategica con los datos ingresados";
    public static final String YA_EXISTE_ACTIVIDAD_DE_GESTION_DE_LA_ACTIVIDAD_ESTRATEGICA_CON_LOS_DATOS_INGRESADOS = "Ya existe la actividad de gestion de la actividad estrategica con los datos ingresados";
    public static final String YA_EXISTE_LA_TAREA_CON_LOS_DATOS_INGRESADOS = "Ya existe la tarea con los datos ingresados";
    public static final String YA_EXISTE_EL_AREA_CON_LOS_DATOS_INGRESADOS = "Ya existe el area con los datos ingresados";
    public static final String YA_EXISTE_EL_CARGO_CON_LOS_DATOS_INGRESADOS = "Ya existe el cargo con los datos ingresados";
    public static final String YA_EXISTE_EL_PAT_CON_LOS_DATOS_INGRESADOS = "Ya existe el pat con los datos ingresados";
    public static final String YA_EXISTE_EL_PROYECTO_CON_LOS_DATOS_INGRESADOS = "Ya existe el proyecto con los datos ingresados";
    public static final String YA_EXISTE_EL_USUARIO_CON_LOS_DATOS_INGRESADOS = "Ya existe el usuario con los datos ingresados";
    public static final String YA_EXISTE_EL_SPRINT_CON_LOS_DATOS_INGRESADOS = "Ya existe el sprint con los datos ingresados";
    public static final String YA_EXISTE_LA_ACTIVIDAD_ESTRATEGICA_CON_LOS_DATOS_INGRESADOS = "Ya existe la actividad estrategica con los datos ingresados";
    public static final String YA_EXISTE_LA_ACTIVIDAD_GESTION_DEL_AREA_CON_LOS_DATOS_INGRESADOS = "Ya existe la actividad gestion del area con los datos ingresados";
}
