package com.ccoa.planeacionestrategica.dominio.modelo.pat.enums;

public enum EProceso {

    AUDITORIAS_DE_CONTROL_INTERNO,
    GESTION_LEGAL,
    GESTION_DE_DERECHOS_DE_PETICION,
    SERVICIOS_TECNOLOGIA_DE_LA_INFORMACION,
    GESTION_DE_LA_INFRAESTRUCTURA_TECNOLOGICA_Y_SISTEMAS_DE_LA_INFORMACION,
    GESTION_DE_LA_SEGURIDAD_DE_LA_INFORMACION,
    GESTION_FINANCIERA,
    GESTION_CONTRACTUAL,
    GESTION_DE_LA_INFRAESTRUCTURA_FISICA,
    GESTION_DOCUMENTAL,
    GESTION_DE_LOS_REGISTROS_PUBLICOS,
    SERVICIOS_PARA_LA_FORMALIZACION,
    SERVICIOS_PARA_EL_DESARROLLO_EMPRESARIAL,
    SERVICIOS_PARA_LA_INTERNACIONALIZACION_Y_ESCALAMIENTO_EMPRESARIAL,
    SERVICIOS_AFILIADOS,
    SERVICIOS_PARA_EL_EMPRENDIMIENTO,
    SERVICIOS_PARA_EL_FORTALECIMIENTO_Y_ACELERACION_EMPRESARIAL,
    SERVICIO_DE_CONCILIACION_ARBITRAJE_Y_AMIGABLE_COMPOSICION,
    SERVICIOS_ESPECIALIZADOS,
    ESTUDIOS_E_INVESTIGACIONES,
    ARTICULACION_PARA_LA_COMPETITIVIDAD,
    RELACIONAMIENTO_INSTITUCIONAL,
    GESTION_DE_COMUNICACIONES,
    GESTION_DE_MERCADEO_Y_SERVICIO_AL_CLIENTE,
    INNOVACION_ORGANIZACIONAL,
    ESTRATEGIA_TECNOLOGICA_Y_TRANSFORMACION_DIGITAL,
    GESTION_DEL_TALENTO_HUMANO,
    GESTION_DE_SEGURIDAD_Y_SALUD_EN_EL_TRABAJO,
    FORMULACION_DESPLIEGUE_Y_SEGUIMIENTO_A_LA_ESTRATEGIA,
    GESTION_DE_LA_CALIDAD,
    GESTION_DE_RIESGOS,
    GESTION_DEL_CONOCIMIENTO,
    TODO_LOS_PROCESOS

    }
