package com.ccoa.planeacionestrategica.infraestructura.clase.actividadgestionactividadestrategica.observacion.adaptador.repositorio.jpa;

import com.ccoa.planeacionestrategica.infraestructura.clase.actividadgestionactividadestrategica.observacion.adaptador.entidad.EntidadObservacionActividadGestionActividadEstrategica;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface RepositorioObservacionActividadGestionActividadEstrategicaJpa extends JpaRepository<EntidadObservacionActividadGestionActividadEstrategica, Long> {
    List<EntidadObservacionActividadGestionActividadEstrategica> findByIdActividadGestionActividadEstrategica(long idActividadGestionActividadEstrategica);
}
