package com.ccoa.planeacionestrategica.dominio.modelo.area.enums;

public enum EDireccion {
    OPERACIONES,COMPETITIVIDAD_Y_DESARROLLO_EMPRESARIAL,RELACIONES_ESTRATEGICAS,
    SECRETARIA_GENERAL,PLANEACION_ESTRATEGICA_Y_GESTION_ORGANIZACIONAL,
    PRESIDENCIA_EJECUTIVA
}
